### PR TITLE
Persistencia de entidad PaymentMethod

### LINKED ISSUE #31: Persistencia de entidad PaymentMethod
**Descripción:** Crear los siguientes archivos para la entidad `PaymentMethod`:

* `PaymentMethodRepository.java`
* `IPaymentMethodService.java`
* `PaymentMethodServiceImpl.java`
* `PaymentMethodController.java`

**Requisitos:**

1. En el archivo `IPaymentMethodService.java`, desarrollar los métodos:
 
```java 
      import java.util.List;
      
      public interface IPaymentMethodService {
          List<PaymentMethod> getAll();
          PaymentMethod getById(Long id);
          PaymentMethod save(PaymentMethod paymentMethod);
          void delete(Long id);
          boolean exists(Long id);
      }
```
  
2. En el archivo `PaymentMethodServiceImpl.java`, implementar los métodos definidos en `IPaymentMethodService.java`.
  
3. En el archivo `PaymentMethodController.java`, desarrollar los endpoints:
  
  * `GET /api/paymentMethod` para obtener todos los `PaymentMethod`.
  * `GET /api/paymentMethod/{id}` para obtener un `PaymentMethod` por ID.
  * `POST /api/paymentMethod` para guardar un nuevo `PaymentMethod`.
  * `PUT /api/paymentMethod/{id}` para actualizar un `PaymentMethod` existente.
  * `DELETE /api/paymentMethod/{id}` para eliminar un `PaymentMethod` por ID.
4. Al crear el pull request, adjuntar capturas de pantalla de todas las llamadas a los métodos a través de Postman.
  

* * *

### PR DESCRIPTION
**Pull request by LeonelMonzon**
…ervice.java PaymentMethodServiceImpl.java PaymentMethodController.java para la entidad PaymentMethod

### CODE REVIEW

**Comment by LeonelMonzon** [comment]
image
image

**Comment by LeonelMonzon** [comment]
image

**Comment by Lmonzon1305** [comment]
image

**Comment by LeonelMonzon** [comment]
image

**Comment by LeonelMonzon** [comment]
image

**Review by ahumadamob — APPROVED** [review]

**Pull request merged**
